databases:
  - name: shop-be-db
    databaseName: shop_be
    user: shop_be_user
    plan: free

services:
  - type: redis
    name: shop-be-redis
    plan: free
    ipAllowList: []

  - type: web
    name: shop-be-web
    plan: free
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/start_services.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shop-be-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: shop-be-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
